/**
 * The shared physically based material library.
 *
 * Every GLB material name is mapped to one of these through
 * `src/data/assets.ts`, so a hand-authored Blender export with the same
 * material names drops straight into the same look.
 *
 * Nothing here is a flat colour: every opaque surface carries albedo,
 * roughness and normal detail generated by `src/lib/surface/`, and the leaf
 * materials are alpha-masked cards with a shared wind shader patch.
 */

import * as THREE from 'three'
import { surfaceTextures, type TextureSet } from './textures'

export const PALETTE = {
  concrete: '#a9b1c2',
  concreteLight: '#c5cbd8',
  render: '#d9d6cd',
  renderWarm: '#d4cebe',
  stone: '#a8a49c',
  sand: '#bda87d',
  metal: '#9ca5b5',
  darkMetal: '#353b49',
  rim: '#ccd3e2',
  asphalt: '#41464f',
  soil: '#7a6449',
  grass: '#5f7040',
  foliage: '#4c6134',
  foliageB: '#5d7040',
  bark: '#5a4630',
  wood: '#6b533a',
  terracotta: '#a05a38',
  mutedPaint: '#4e5e6e',
  glass: '#203244',
  glassDark: '#0d1623',
  paintA: '#ccd1de',
  paintB: '#28303f',
  paintC: '#8d4a34',
  paintD: '#d8d3c6',
  rubber: '#141414',
  safety: '#c99a1e',
  accent: '#4a7bff',
  black: '#060b17',
  charcoal: '#101c33',
  muted: '#8395bb',
  brick: '#8d5138',
  white: '#eef4ff',
} as const

/* -------------------------------------------------------------------- wind */

export const windUniforms = {
  uTime: { value: 0 },
  uWind: { value: 0.6 },
}

const windPars = /* glsl */ `
  uniform float uTime;
  uniform float uWind;
`

const windBody = /* glsl */ `
  #ifdef USE_INSTANCING
    vec3 windWorld = ( modelMatrix * instanceMatrix * vec4( transformed, 1.0 ) ).xyz;
  #else
    vec3 windWorld = ( modelMatrix * vec4( transformed, 1.0 ) ).xyz;
  #endif
  float windPhase = windWorld.x * 0.21 + windWorld.z * 0.17;
  float windHeight = max( transformed.y, 0.0 );
  float windSway = sin( uTime * 0.85 + windPhase ) * 0.62 + sin( uTime * 0.31 + windPhase * 1.9 ) * 0.38;
  float windGust = 0.62 + 0.38 * sin( uTime * 0.09 + windPhase * 0.04 );
  float windAmp = uWind * ( 0.019 * windHeight + 0.0016 * windHeight * windHeight );
  transformed.x += windSway * windAmp * windGust;
  transformed.z += windSway * windAmp * 0.72 * windGust;
`

/**
 * Vertex-level wind. Amplitude grows with height, phase varies across the
 * world so nothing moves in unison, and a slow gust envelope keeps it from
 * reading as a loop.
 */
export function applyWind(material: THREE.Material, strength = 1) {
  const target = material as THREE.MeshStandardMaterial & { userData: Record<string, unknown> }
  target.userData.windStrength = strength
  target.onBeforeCompile = (shader) => {
    shader.uniforms.uTime = windUniforms.uTime
    shader.uniforms.uWind = { value: strength }
    shader.vertexShader = shader.vertexShader
      .replace('#include <common>', `#include <common>\n${windPars}`)
      .replace('#include <begin_vertex>', `#include <begin_vertex>\n${windBody}`)
  }
  target.customProgramCacheKey = () => `wind-${strength}`
  return target
}

/* ------------------------------------------------------------------ helpers */

const cache = new Map<string, THREE.Material>()

function memo<T extends THREE.Material>(key: string, make: () => T): T {
  const hit = cache.get(key)
  if (hit) return hit as T
  const material = make()
  cache.set(key, material)
  return material
}

type SurfaceMaterialOptions = {
  /** draw over the ground without fighting it */
  depthWrite?: boolean
  polygonOffset?: boolean
  polygonOffsetFactor?: number
  polygonOffsetUnits?: number
  color?: string | number
  roughness?: number
  metalness?: number
  normalScale?: number
  envMapIntensity?: number
  repeat?: number
  alphaTest?: number
  transparent?: boolean
  opacity?: number
  side?: THREE.Side
  wind?: number
  emissive?: string
  emissiveIntensity?: number
  flatShaded?: boolean
  vertexColors?: boolean
}

function fromSurface(
  key: string,
  surface: string,
  size: 256 | 512,
  options: SurfaceMaterialOptions = {},
): THREE.MeshStandardMaterial {
  return memo(`${key}-${surface}-${size}-${JSON.stringify(options)}`, () => {
    const set: TextureSet | null = surfaceTextures(surface, size)
    const repeat = options.repeat ?? 1
    const clone = (texture: THREE.Texture | undefined) => {
      if (!texture) return undefined
      if (repeat === 1) return texture
      const copy = texture.clone()
      copy.needsUpdate = true
      copy.repeat.set(repeat, repeat)
      return copy
    }
    const material = new THREE.MeshStandardMaterial({
      color: new THREE.Color(options.color ?? 0xffffff),
      map: set ? clone(set.map) : undefined,
      normalMap: set ? clone(set.normalMap) : undefined,
      roughnessMap: set ? clone(set.roughnessMap) : undefined,
      roughness: options.roughness ?? 0.85,
      metalness: options.metalness ?? 0.05,
      envMapIntensity: options.envMapIntensity ?? 0.6,
      flatShading: options.flatShaded ?? false,
    })
    if (set && options.normalScale !== undefined) {
      material.normalScale = new THREE.Vector2(options.normalScale, options.normalScale)
    }
    if (options.alphaTest !== undefined) {
      material.alphaTest = options.alphaTest
      material.transparent = false
    }
    if (options.transparent) {
      material.transparent = true
      material.opacity = options.opacity ?? 1
    }
    if (options.depthWrite !== undefined) material.depthWrite = options.depthWrite
    if (options.polygonOffset) {
      material.polygonOffset = true
      material.polygonOffsetFactor = options.polygonOffsetFactor ?? -2
      material.polygonOffsetUnits = options.polygonOffsetUnits ?? -2
    }
    if (options.side) material.side = options.side
    if (options.vertexColors) material.vertexColors = true
    if (options.emissive) {
      material.emissive = new THREE.Color(options.emissive)
      material.emissiveIntensity = options.emissiveIntensity ?? 1
    }
    if (options.wind) applyWind(material, options.wind)
    return material
  }) as THREE.MeshStandardMaterial
}

function plain(
  key: string,
  options: THREE.MeshStandardMaterialParameters & { wind?: number },
): THREE.MeshStandardMaterial {
  const { wind, ...params } = options
  return memo(`plain-${key}-${JSON.stringify(params)}-${wind ?? 0}`, () => {
    const material = new THREE.MeshStandardMaterial(params)
    if (wind) applyWind(material, wind)
    return material
  }) as THREE.MeshStandardMaterial
}

/* -------------------------------------------------------------------- road */

/** Material for a part produced by `buildRoadParts()`. */
export function roadPartMaterial(
  part: { key: string; color?: string; opacity?: number },
  size: 256 | 512 = 256,
): THREE.MeshStandardMaterial {
  switch (part.key) {
    case 'gravel':
      return roadGravelMaterial(size)
    case 'soil':
      return roadSoilMaterial(size)
    case 'paint':
      return roadPaintMaterial(size, part.opacity ?? 1)
    case 'patch':
      return asphaltPatchMaterial(size)
    case 'film':
      return roadFilmMaterial(part.color ?? '#6a6255', part.opacity ?? 0.22)
    case 'kerb':
      return concreteMaterial('light', 1, size)
    case 'drain':
      return concreteMaterial('dark', 1, size)
    case 'hole':
      return plain('road-hole', { color: 0x232323, roughness: 1, metalness: 0 })
    default:
      return roadAsphaltMaterial(size)
  }
}

/* ------------------------------------------------------------ architecture */

export function concreteMaterial(
  variant: 'mid' | 'dark' | 'light' | 'stone' = 'mid',
  repeat = 1,
  size: 256 | 512 = 256,
) {
  if (variant === 'stone') return stoneMaterial(size, false)
  const surface = variant === 'dark' ? 'concreteDark' : variant === 'light' ? 'concreteLight' : 'concrete'
  return fromSurface(`concrete-${variant}`, surface, size, {
    color: variant === 'dark' ? 0x8d8a85 : variant === 'light' ? 0xc6c0b4 : 0xa9a49a,
    roughness: 0.94,
    metalness: 0.04,
    envMapIntensity: 0.45,
    normalScale: 0.85,
    repeat,
  })
}

export function renderMaterial(size: 256 | 512 = 256, variant: 'render' | 'renderWarm' | 'renderOld' = 'render') {
  return fromSurface(`render-${variant}`, variant, size, {
    color: variant === 'renderOld' ? 0x9d9483 : 0xffffff,
    roughness: 0.86,
    metalness: 0.02,
    envMapIntensity: 0.4,
    normalScale: 0.7,
  })
}

export function stoneMaterial(size: 256 | 512 = 256, blocky = false) {
  return fromSurface(`stone-${blocky ? 'block' : 'plain'}`, blocky ? 'stoneBlock' : 'stone', size, {
    color: 0xa89a80,
    roughness: 0.9,
    metalness: 0.03,
    envMapIntensity: 0.4,
    normalScale: 0.9,
  })
}

export function brickMaterial(size: 256 | 512 = 256) {
  return fromSurface('brick', 'brick', size, {
    color: 0xffffff,
    roughness: 0.92,
    metalness: 0.0,
    envMapIntensity: 0.35,
    normalScale: 1,
  })
}

export function asphaltMaterial(size: 256 | 512 = 512) {
  return fromSurface('asphalt', 'asphalt', size, {
    color: 0x55565a,
    roughness: 0.92,
    metalness: 0.03,
    envMapIntensity: 0.28,
    normalScale: 0.8,
  })
}

/** Damp, dirt-stained plinth course under the boundary wall. */
export function plinthMaterial(size: 256 | 512 = 256) {
  return fromSurface('plinth', 'concreteDark', size, {
    color: 0x7d766a,
    roughness: 0.98,
    metalness: 0.03,
    envMapIntensity: 0.3,
    normalScale: 0.9,
  })
}

/**
 * Road surfaces carry a per-vertex macro tint: broad tonal drift along the
 * length, polished wheel paths and dust drifted in from the verge (see
 * `road-geometry.ts`). The tint is what keeps a 1 km road from reading as one
 * repeated texture, so these three are separate from the shared materials used
 * by patches that have no colour attribute.
 */
export function roadAsphaltMaterial(size: 256 | 512 = 512) {
  return fromSurface('road-asphalt', 'asphalt', size, {
    // weathered and dusted: fresh asphalt is near-black, a working Indian
    // carriageway after a few seasons is not
    color: 0x63646a,
    roughness: 0.92,
    metalness: 0.03,
    envMapIntensity: 0.28,
    normalScale: 0.8,
    vertexColors: true,
  })
}

export function roadGravelMaterial(size: 256 | 512 = 256) {
  return fromSurface('road-gravel', 'gravel', size, {
    color: 0xffffff,
    roughness: 1,
    metalness: 0,
    envMapIntensity: 0.2,
    normalScale: 1.1,
    vertexColors: true,
  })
}

export function roadSoilMaterial(size: 256 | 512 = 256) {
  return fromSurface('road-soil', 'soilDry', size, {
    color: 0xffffff,
    roughness: 1,
    metalness: 0,
    envMapIntensity: 0.25,
    normalScale: 1,
    vertexColors: true,
  })
}

export function roadPaintMaterial(size: 256 | 512 = 256, opacity = 1) {
  return fromSurface('road-paint', 'roadPaint', size, {
    color: 0xfff8e8,
    roughness: 0.74,
    metalness: 0,
    envMapIntensity: 0.2,
    normalScale: 0.3,
    alphaTest: 0.35,
    opacity,
  })
}

/** A patched / re-laid section of carriageway — different pour, different age. */
export function asphaltPatchMaterial(size: 256 | 512 = 512) {
  return fromSurface('asphalt-patch', 'asphaltPatch', size, {
    color: 0x66676a,
    roughness: 0.9,
    metalness: 0.03,
    envMapIntensity: 0.25,
    normalScale: 0.7,
  })
}

/** Dust / tyre-polished film laid over the carriageway. */
export function roadFilmMaterial(color = '#6a6255', opacity = 0.22) {
  return memo(`road-film-${color}-${opacity}`, () =>
    new THREE.MeshStandardMaterial({
      color: new THREE.Color(color),
      roughness: 1,
      metalness: 0,
      transparent: true,
      opacity,
      depthWrite: false,
      polygonOffset: true,
      polygonOffsetFactor: -2,
      polygonOffsetUnits: -2,
    }),
  )
}

export function soilMaterial(size: 256 | 512 = 256, dry = false) {
  return fromSurface(`soil-${dry ? 'dry' : 'damp'}`, dry ? 'soilDry' : 'soil', size, {
    color: 0xffffff,
    roughness: 1,
    metalness: 0,
    envMapIntensity: 0.25,
    normalScale: 1,
  })
}

export function gravelMaterial(size: 256 | 512 = 256) {
  return fromSurface('gravel', 'gravel', size, {
    color: 0xffffff,
    roughness: 1,
    metalness: 0,
    envMapIntensity: 0.2,
    normalScale: 1.1,
  })
}

export function terrainMaterial(
  surface: 'soil' | 'soilDry' | 'grass' | 'gravel',
  size: 256 | 512 = 256,
) {
  return fromSurface(`terrain-${surface}`, surface, size, {
    color: 0xffffff,
    roughness: 1,
    metalness: 0,
    envMapIntensity: 0.28,
    normalScale: 1,
    vertexColors: true,
  })
}

export function grassMaterial(size: 256 | 512 = 256) {
  return fromSurface('grass-ground', 'grass', size, {
    color: 0xffffff,
    roughness: 0.9,
    metalness: 0,
    envMapIntensity: 0.3,
    normalScale: 0.8,
  })
}

/**
 * Ground-cover blade cards. Driven by the shared wind clock so the whole
 * ground cover breathes together with the tree canopies.
 */
export function bladeMaterial(dry = false, size: 256 | 512 = 256, wind = 1) {
  return fromSurface(`blades-${dry ? 'dry' : 'green'}`, dry ? 'bladesDry' : 'blades', size, {
    color: 0xffffff,
    roughness: 0.78,
    metalness: 0,
    envMapIntensity: 0.32,
    alphaTest: 0.5,
    side: THREE.DoubleSide,
    normalScale: 0.4,
    wind,
  })
}

/**
 * Soft-edged ground patch (dust drift, compacted yard, spill, repair).
 * Transparent, alpha carried by the vertex colour, drawn just above the ground
 * with a polygon offset so it can never z-fight the terrain.
 */
export function patchMaterial(
  surface: 'soil' | 'soilDry' | 'gravel' | 'asphalt' | 'asphaltPatch' | 'concrete' | 'sand' = 'soilDry',
  size: 256 | 512 = 256,
  opacity = 0.85,
) {
  const mapSurface = surface === 'sand' ? 'soilDry' : surface
  return fromSurface(`patch-${mapSurface}-${opacity}`, mapSurface, size, {
    color: surface === 'sand' ? 0xd8c69b : 0xffffff,
    roughness: 1,
    metalness: 0,
    envMapIntensity: 0.18,
    normalScale: 0.6,
    vertexColors: true,
    transparent: true,
    opacity,
    depthWrite: false,
    polygonOffset: true,
    polygonOffsetFactor: -6,
    polygonOffsetUnits: -6,
  })
}

/* ---------------------------------------------------------------- surfaces */

export function metalMaterial(
  variant: 'brushed' | 'dark' | 'rust' | 'bright' | 'accent' = 'brushed',
  repeat = 1,
  size: 256 | 512 = 256,
) {
  if (variant === 'accent') {
    return fromSurface('metal-accent', 'metalRust', size, {
      color: 0x4a7bff,
      roughness: 0.68,
      metalness: 0.7,
      envMapIntensity: 0.8,
      normalScale: 0.8,
      repeat,
    })
  }
  const surface = variant === 'rust' ? 'metalRust' : variant === 'dark' ? 'metalDark' : 'metal'
  const color = variant === 'bright' ? 0xd2d2d2 : variant === 'dark' ? 0x8b8d90 : variant === 'rust' ? 0xb08a6c : 0xb9b7b2
  return fromSurface(`metal-${variant}`, surface, size, {
    color,
    roughness: variant === 'brushed' ? 0.42 : variant === 'bright' ? 0.3 : variant === 'dark' ? 0.55 : 0.72,
    metalness: variant === 'rust' ? 0.55 : 0.9,
    envMapIntensity: 0.9,
    normalScale: variant === 'rust' ? 0.8 : 0.35,
    repeat,
  })
}

/**
 * Replacement cladding sheet.
 *
 * A weathered, slightly oxidised galvalume panel: the sheet that gets bolted
 * over a damaged one and never matches. Registered separately from `metal` so
 * a building can carry one or two without tinting every other sheet on it.
 */
export function metalRibMaterial(size: 256 | 512 = 256) {
  return fromSurface('metal-rib', 'metal', size, {
    color: 0x9fa3a1,
    roughness: 0.62,
    metalness: 0.78,
    envMapIntensity: 0.7,
    normalScale: 0.5,
  })
}

export function woodMaterial(size: 256 | 512 = 256) {
  return fromSurface('wood-bark', 'bark', size, {
    color: 0x8a7256,
    roughness: 0.95,
    metalness: 0,
    envMapIntensity: 0.25,
    normalScale: 1.1,
    wind: 0.35,
  })
}

/**
 * Glazing.
 *
 * Alpha blending scales everything the material produces, including the sky
 * reflection — at 0.32 opacity a bright sky bounced off the facade arrived at
 * a third of its value, which is why the towers read as dark glass. Real
 * architectural glazing is mostly *reflection*: you see the sky and a hint of
 * the interior behind it. Opacity is therefore high enough for the reflection
 * to survive the blend, and roughness stays low so the reflection is a sky,
 * not a haze.
 *
 * Note: three overrides `envMapIntensity` with `scene.environmentIntensity`
 * whenever a standard material has no explicit `envMap` (which is our case —
 * the environment comes from `scene.environment`), so the reflection strength
 * is set once, in `src/lib/daylight.ts`.
 */
export function glassMaterial(tint = '#26343a', opacity = 0.58, roughness = 0.05) {
  return memo(`glass-${tint}-${opacity}-${roughness}`, () =>
    new THREE.MeshStandardMaterial({
      color: new THREE.Color(tint),
      roughness,
      metalness: 0.0,
      transparent: true,
      opacity,
      envMapIntensity: 1.7,
      side: THREE.DoubleSide,
      depthWrite: false,
    }),
  )
}

/**
 * Solar PV module.
 *
 * A panel is dark blue glass over an absorber, not black metal: near-black
 * base colour with high metalness reflects almost nothing, so the arrays read
 * as holes in the ground. Kept as a glossy dielectric instead, so they take the
 * sun as a specular highlight and the sky as a sheen — which is what a solar
 * farm actually looks like at midday.
 */
export function panelMaterial() {
  return memo('panel-dark', () =>
    new THREE.MeshStandardMaterial({
      color: new THREE.Color('#152a41'),
      roughness: 0.11,
      metalness: 0.4,
      envMapIntensity: 1.5,
    }),
  )
}

export function paintMaterial(color: string, roughness = 0.28, size: 256 | 512 = 256) {
  return fromSurface(`paint-${color}`, 'paint', size, {
    color,
    roughness,
    metalness: 0.35,
    envMapIntensity: 1.05,
    normalScale: 0.35,
  })
}

/**
 * Tyre rubber.
 *
 * #151516 is 0.006 in linear light — a hole. Real sidewall rubber sits around
 * 0.03–0.05, which under direct sun reads as dark grey with the tread still
 * legible; the old value read as a black cut-out under every vehicle and was
 * part of why the scene felt underexposed.
 */
export function rubberMaterial() {
  return memo('rubber', () =>
    new THREE.MeshStandardMaterial({
      color: new THREE.Color('#333436'),
      roughness: 0.88,
      metalness: 0,
      envMapIntensity: 0.2,
    }),
  )
}

export function plasticMaterial(color = '#5a5f58') {
  return memo(`plastic-${color}`, () =>
    new THREE.MeshStandardMaterial({
      color: new THREE.Color(color),
      roughness: 0.55,
      metalness: 0.02,
      envMapIntensity: 0.5,
    }),
  )
}

export function lightMaterial(color: string, intensity = 0.35) {
  return memo(`lamp-${color}-${intensity}`, () =>
    new THREE.MeshStandardMaterial({
      color: new THREE.Color(color),
      emissive: new THREE.Color(color),
      emissiveIntensity: intensity,
      roughness: 0.25,
      metalness: 0,
    }),
  )
}

/* ----------------------------------------------------------------- foliage */

export function leafMaterial(variant: 'leaf' | 'leafWarm' | 'leafDry' = 'leaf', size: 256 | 512 = 256) {
  return fromSurface(`leaf-${variant}`, variant, size, {
    color: 0xffffff,
    roughness: 0.72,
    metalness: 0,
    envMapIntensity: 0.35,
    alphaTest: 0.5,
    side: THREE.DoubleSide,
    normalScale: 0.5,
    wind: 1,
  })
}

/**
 * The darkness inside a window.
 *
 * Rooms are several stops below a sunlit facade, so this is deliberately
 * almost black in albedo terms (linear ≈ 0.005) — even where direct sun finds
 * its way through an opening it stays darker than any exterior surface, which
 * is what your eye expects from glass on a building.
 */
export function interiorMaterial() {
  return memo('interior', () =>
    new THREE.MeshStandardMaterial({
      color: new THREE.Color('#0d0f10'),
      roughness: 0.95,
      metalness: 0,
      envMapIntensity: 0.15,
    }),
  )
}

/**
 * Leaves on the shaded side of the crown.
 *
 * A crown is never one green: the leaves that face the sun are bright
 * yellow-green, the ones buried inside it are darker, greener and softer.
 * Painting every leaf with the same albedo is a large part of why foliage reads
 * as a synthetic mass. The builder picks this material for any leaf whose
 * distance from the crown centre puts it in the interior, so the gradient is
 * structural rather than a texture trick.
 */
export function leafDeepMaterial(variant: 'leaf' | 'leafWarm' | 'leafDry' = 'leaf', size: 256 | 512 = 256) {
  return fromSurface(`leaf-deep-${variant}`, variant, size, {
    color: 0xb4c09c,
    roughness: 0.84,
    metalness: 0,
    envMapIntensity: 0.35,
    alphaTest: 0.5,
    side: THREE.DoubleSide,
    normalScale: 0.5,
    wind: 1,
  })
}

export function foliageMaterial(color: string = PALETTE.foliage, size: 256 | 512 = 256) {
  return fromSurface(`foliage-${color}`, 'leaf', size, {
    color,
    roughness: 0.78,
    metalness: 0,
    envMapIntensity: 0.3,
    side: THREE.DoubleSide,
    wind: 0.5,
  })
}

/* ------------------------------------------------------------------- utils */

export function emissiveMaterial(color: string, intensity = 1, opacity = 1) {
  return memo(`emissive-${color}-${intensity}-${opacity}`, () =>
    new THREE.MeshStandardMaterial({
      color: new THREE.Color(color),
      emissive: new THREE.Color(color),
      emissiveIntensity: intensity,
      roughness: 0.4,
      metalness: 0,
      transparent: opacity < 1,
      opacity,
    }),
  )
}

/**
 * Vehicle interior trim — seats, dash, door cards.
 *
 * Deliberately not black. A car cabin in daylight is several stops below the
 * exterior, but pure black behind 58 % glass reads as a hole punched clean
 * through the car rather than as an upholstered space, so this sits just above
 * the `interior` material: dark enough to stay recessed, light enough that the
 * seat backs and headrests are legible as shapes.
 */
export function trimMaterial() {
  return plain('trim', { color: new THREE.Color('#23272b'), roughness: 0.84, metalness: 0 })
}

/**
 * Vehicle paint.
 *
 * The old car paint was `metalness 0.35`, which is the single most common
 * reason a painted surface reads as plastic or as a toy: on a metalness workflow
 * the base colour *becomes* the specular reflectance, so a third of the paint's
 * brightness turns into a coloured sheen and the diffuse goes muddy. Real
 * automotive paint is a dielectric with a clear lacquer on top — metalness 0,
 * low-ish roughness, and a bit more environment than a wall gets.
 *
 * Roughness is 0.34 rather than a showroom 0.05: these are site vehicles that
 * have been parked outside.
 */
export function carPaintMaterial(color: string, size: 256 | 512 = 256) {
  return fromSurface(`carpaint-${color}`, 'paint', size, {
    color,
    roughness: 0.34,
    metalness: 0,
    envMapIntensity: 1.25,
    normalScale: 0.28,
  })
}

export function flatMaterial(color: string, opacity = 1) {
  return memo(`flat-${color}-${opacity}`, () =>
    new THREE.MeshBasicMaterial({ color: new THREE.Color(color), transparent: opacity < 1, opacity }),
  )
}

/** Soft radial blob used as a fake contact shadow / pooling decal. */
let radialTexture: THREE.Texture | null = null
export function decalMaterial(color = '#000000', opacity = 0.5) {
  return memo(`decal-${color}-${opacity}`, () => {
    if (!radialTexture) {
      const size = 128
      const data = new Uint8Array(size * size * 4)
      for (let y = 0; y < size; y++) {
        for (let x = 0; x < size; x++) {
          const dx = (x / size) * 2 - 1
          const dy = (y / size) * 2 - 1
          const d = Math.min(1, Math.sqrt(dx * dx + dy * dy))
          const i = (y * size + x) * 4
          data[i] = 255
          data[i + 1] = 255
          data[i + 2] = 255
          data[i + 3] = Math.round(Math.pow(1 - d, 2.4) * 255)
        }
      }
      radialTexture = new THREE.DataTexture(data, size, size, THREE.RGBAFormat)
      radialTexture.colorSpace = THREE.SRGBColorSpace
      radialTexture.needsUpdate = true
    }
    return new THREE.MeshBasicMaterial({
      color: new THREE.Color(color),
      alphaMap: radialTexture,
      transparent: true,
      opacity,
      depthWrite: false,
    })
  })
}

/** India map states: natural stone, not neon. */
export function stateBaseMaterial(size: 256 | 512 = 256) {
  return fromSurface('state-base', 'stone', size, {
    color: 0x8d8571,
    roughness: 0.82,
    metalness: 0.12,
    envMapIntensity: 0.55,
    normalScale: 0.6,
  })
}

/* -------------------------------------------------------------- key mapping */

export type MaterialKey = string

/**
 * GLB material name → shared material.
 *
 * The GLB generator uses the same names as an artist would in Blender, so a
 * real export needs no code changes.
 */
export function materialForKey(
  key: string,
  quality: { textureSize: 256 | 512; shade?: boolean },
): THREE.Material {
  const size = quality.textureSize
  switch (key) {
    case 'concrete':
      return concreteMaterial('mid', 1, size)
    case 'darkConcrete':
      return concreteMaterial('dark', 1, size)
    case 'lightConcrete':
      return concreteMaterial('light', 1, size)
    case 'render':
      return renderMaterial(size, 'render')
    case 'renderWarm':
      return renderMaterial(size, 'renderWarm')
    case 'renderOld':
      return renderMaterial(size, 'renderOld')
    case 'stone':
      return stoneMaterial(size, false)
    case 'stoneBlock':
      return stoneMaterial(size, true)
    case 'brick':
      return brickMaterial(size)
    case 'asphalt':
      return asphaltMaterial(size)
    case 'roadPaint':
      return roadPaintMaterial(size)
    case 'asphaltPatch':
      return asphaltPatchMaterial(size)
    case 'soil':
      return soilMaterial(size, false)
    case 'soilDry':
      return soilMaterial(size, true)
    case 'gravel':
      return gravelMaterial(size)
    case 'grass':
      return grassMaterial(size)
    case 'sand':
      return plain('sand', { color: new THREE.Color(PALETTE.sand), roughness: 1, metalness: 0 })
    case 'wood':
    case 'bark':
      return woodMaterial(size)
    case 'metal':
      return metalMaterial('brushed', 1, size)
    case 'metalRib':
      return metalRibMaterial(size)
    case 'darkMetal':
      return metalMaterial('dark', 1, size)
    case 'rim':
      return metalMaterial('bright', 1, size)
    case 'rust':
      return metalMaterial('rust', 1, size)
    case 'glass':
      return glassMaterial(PALETTE.glass, 0.58)
    case 'glassDark':
      return glassMaterial(PALETTE.glassDark, 0.68, 0.09)
    case 'leafDeep':
      return leafDeepMaterial('leaf', size)
    case 'leafBDeep':
      return leafDeepMaterial('leafWarm', size)
    case 'interior':
      return interiorMaterial()
    case 'panelDark':
      return panelMaterial()
    case 'plastic':
      return plasticMaterial('#5c625a')
    case 'carA':
      return carPaintMaterial(PALETTE.paintA)
    case 'paintA':
      return paintMaterial(PALETTE.paintA, 0.24)
    case 'carB':
      return carPaintMaterial(PALETTE.paintB)
    case 'paintB':
      return paintMaterial(PALETTE.paintB, 0.3)
    case 'carC':
      return carPaintMaterial(PALETTE.paintC)
    case 'paintC':
      return paintMaterial(PALETTE.paintC, 0.28)
    case 'carD':
      return carPaintMaterial(PALETTE.paintD)
    case 'paintD':
      return paintMaterial(PALETTE.paintD, 0.32)
    case 'paintMuted':
      return paintMaterial(PALETTE.mutedPaint, 0.55)
    case 'safety':
      return paintMaterial(PALETTE.safety, 0.6)
    case 'rubber':
      return rubberMaterial()
    case 'light':
      return lightMaterial('#f2f0e2', 0.25)
    case 'tail':
      return lightMaterial('#8e1f14', 0.15)
    case 'plate':
      return plasticMaterial('#d8d4c4')
    case 'trim':
      return trimMaterial()
    case 'sack':
      return fromSurface('sack', 'render', size, { color: 0xcfc8b6, roughness: 0.95, metalness: 0 })
    case 'tarp':
      return fromSurface('tarp', 'metalDark', size, { color: 0x44525a, roughness: 0.7, metalness: 0.1 })
    case 'terracotta':
      return plain('terracotta', { color: new THREE.Color(PALETTE.terracotta), roughness: 0.8, metalness: 0 })
    case 'leaf':
      return leafMaterial('leaf', size)
    case 'leafB':
    case 'leafWarm':
      return leafMaterial('leafWarm', size)
    case 'leafDry':
      return leafMaterial('leafDry', size)
    case 'foliage':
      return foliageMaterial(PALETTE.foliage, size)
    case 'foliageB':
      return foliageMaterial(PALETTE.foliageB, size)
    default:
      return concreteMaterial('mid', 1, size)
  }
}

export function disposeMaterials() {
  cache.forEach((material) => material.dispose())
  cache.clear()
}
