import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // generated by tools/headless-scene.mjs (verification harness output)
    ".headless-build/**",
    ".headless-tsconfig.json",
  ]),
  {
    files: ["src/components/three/**/*.{ts,tsx}", "src/sections/**/*.tsx"],
    rules: {
      /**
       * React Three Fiber scenes are imperative by design: every frame mutates
       * Object3D transforms, materials and refs inside useFrame, and refs are
       * read to configure controls. The React Compiler's purity/immutability
       * analysis models render-phase data flow, not a render loop, so these
       * rules would flag the idiomatic R3F pattern on every scene.
       */
      "react-hooks/immutability": "off",
      "react-hooks/refs": "off",
      "react-hooks/purity": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
  {
    files: ["tools/**/*.mjs"],
    rules: {
      // the harness re-implements react's hook semantics on purpose
      "react-hooks/exhaustive-deps": "off",
    },
  },
]);

export default eslintConfig;
