/**
 * GLB inspection / QA.
 *
 * Reads production GLBs and writes `docs/3d/ASSET_QA_REPORT.md`. Every asset is
 * checked for size, triangles, meshes, materials, textures, bounds, normals and
 * UVs — the same gates a photographer/technical-artist would run before a model
 * can enter the browser.
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { NodeIO } from '@gltf-transform/core'
import { boundsForFile } from './bounds.mjs'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '../..')
const ASSET_DIR = path.join(ROOT, 'public/assets/glb')
const REPORT_PATH = path.join(ROOT, 'docs/3d/ASSET_QA_REPORT.md')

const io = new NodeIO()
const rows = []

for (const file of fs.readdirSync(ASSET_DIR).filter((f) => f.endsWith('.glb')).sort()) {
  const doc = await io.read(path.join(ASSET_DIR, file))
  const root = doc.getRoot()
  const meshes = root.listMeshes()
  const materials = root.listMaterials()
  const textures = root.listTextures()
  const nodes = root.listNodes()

  let triangles = 0
  let vertices = 0
  let hasNormals = true
  let hasUvs = true
  let hasNaN = false
  let hasInfinity = false

  for (const mesh of meshes) {
    for (const prim of mesh.listPrimitives()) {
      const pos = prim.getAttribute('POSITION')
      const inputs = prim.listSemantics()
      triangles += prim.getIndices() ? prim.getIndices().getCount() / 3 : pos.getCount() / 3
      vertices += pos.getCount()
      hasNormals = hasNormals && inputs.includes('NORMAL')
      hasUvs = hasUvs && inputs.includes('TEXCOORD_0')
      // finite-ness is checked on the de-quantised world-space vertices
      void pos
    }
  }

  // world-space measurement (de-quantised, node transforms applied)
  const bounds = boundsForFile(path.join(ASSET_DIR, file))
  for (const value of bounds.points) {
    if (Number.isNaN(value)) hasNaN = true
    if (!Number.isFinite(value)) hasInfinity = true
  }
  const size = fs.statSync(path.join(ASSET_DIR, file)).size
  rows.push({
    file,
    size,
    triangles: Math.round(triangles),
    vertices,
    meshes: meshes.length,
    materials: materials.length,
    textures: textures.length,
    nodes: nodes.length,
    normals: hasNormals,
    uvs: hasUvs,
    hasNaN,
    hasInfinity,
    min: bounds.min.map((v) => v.toFixed(2)),
    max: bounds.max.map((v) => v.toFixed(2)),
  })
}

const allPass = rows.every((r) => r.triangles < 250000 && r.size < 4_000_000 && r.normals && r.uvs && !r.hasNaN && !r.hasInfinity)
const lines = [
  '# 3D Asset QA Report',
  '',
  `> Generated by \`npm run assets:inspect\` on ${new Date().toISOString().slice(0, 10)}.`,
  '',
  '| Asset | Size | Triangles | Vertices | Meshes | Materials | Textures | Nodes | Normals | UVs | Finite | Bounds (min → max) |',
  '| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |',
  ...rows.map(
    (r) =>
      `| ${r.file} | ${(r.size / 1024).toFixed(1)} kB | ${r.triangles.toLocaleString()} | ${r.vertices.toLocaleString()} | ${r.meshes} | ${r.materials} | ${r.textures} | ${r.nodes} | ${r.normals ? '✅' : '❌'} | ${r.uvs ? '✅' : '❌'} | ${!r.hasNaN && !r.hasInfinity ? '✅' : '❌'} | ${r.min.join(', ')} → ${r.max.join(', ')} |`,
  ),
  '',
  '## Production gates',
  '',
  ...rows.map(
    (r) =>
      `- [${allPass ? 'x' : ' '}] ${r.file} — ${r.size < 4_000_000 ? 'size OK' : 'TOO LARGE'}, ${r.triangles < 250_000 ? 'polycount OK' : 'TOO DENSE'}, ${r.normals ? 'normals OK' : 'MISSING NORMALS'}, ${r.uvs ? 'UVs OK' : 'MISSING UVS'}, ${!r.hasNaN && !r.hasInfinity ? 'finite OK' : 'INVALID NUMBERS'}`,
  ),
  '',
  `## Verdict`,
  '',
  allPass
    ? 'All production GLBs pass the browser quality gates.'
    : '❌ One or more assets fail a production gate. Re-run the generation step before release.',
  '',
  '## Notes',
  '',
  '- Textures are intentionally not baked into these GLBs; the runtime material library applies procedural PBR maps via the asset registry.',
  '- The asset registry (`src/data/assets.ts`) maps GLB material names to the shared concrete / stone / glass / metal / foliage materials.',
  '- Replacing an asset with a Blender/photogrammetry export: drop the GLB into `public/assets/glb/`, keep the same filename (or update `src/data/assets.ts`).',
  '',
]

fs.writeFileSync(REPORT_PATH, lines.join('\n'))
console.log(`→ wrote ${REPORT_PATH} (${rows.length} assets)`)
