/**
 * Visual QA scoring.
 *
 * This stage scores the production-grade asset set against hard, reproducible
 * quality gate contributors — silhouette/complexity, real-world scale,
 * material separation, structural detail and grounding. It deliberately does
 * NOT pretend to be a photograph. The score is the engineering-informed
 * baseline; the final label requires the on-screen render pass documented in
 * `docs/3d/VISUAL_ASSET_QA.md`.
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { NodeIO } from '@gltf-transform/core'
import { boundsForFile } from './bounds.mjs'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '../..')
const ASSET_DIR = path.join(ROOT, 'public/assets/glb')
const REPORT_PATH = path.join(ROOT, 'docs/3d/VISUAL_ASSET_QA.md')

const io = new NodeIO()
const rows = []

function clamp(value) {
  return Math.max(1, Math.min(10, value))
}

function separateReflection(materials) {
  return materials.some((m) => m.getMetallicFactor() > 0.4 && m.getRoughnessFactor() < 0.5)
}

for (const file of fs.readdirSync(ASSET_DIR).filter((f) => f.endsWith('.glb')).sort()) {
  const doc = await io.read(path.join(ASSET_DIR, file))
  const root = doc.getRoot()
  const meshes = root.listMeshes()
  const materials = root.listMaterials()

  let triangles = 0
  const normalRich = new Set()
  for (const mesh of meshes) {
    for (const prim of mesh.listPrimitives()) {
      const pos = prim.getAttribute('POSITION')
      const array = []
      triangles += prim.getIndices() ? prim.getIndices().getCount() / 3 : (pos?.getCount() ?? 0) / 3
      const normals = prim.getAttribute('NORMAL')?.getArray()
      if (normals) {
        for (let i = 0; i < normals.length; i += 3) {
          normalRich.add(`${Math.round(normals[i] * 18)},${Math.round(normals[i + 1] * 18)},${Math.round(normals[i + 2] * 18)}`)
        }
      }
      void array
    }
  }
  // world-space measurement (de-quantised, node transforms applied)
  const bounds = boundsForFile(path.join(ASSET_DIR, file))
  const min = bounds.min
  const max = bounds.max
  const [width, height, depth] = bounds.size
  // below-ground geometry is legitimate for footings and piers
  const grounded = min[1] <= 0.25 && min[1] >= -0.8
  const sizeKB = fs.statSync(path.join(ASSET_DIR, file)).size / 1024

  // Richness = material separation + angled normal detail + structural mass.
  const separation = clamp(materials.length)
  const normalRichness = clamp(normalRich.size / 60)
  const massRichness = clamp(triangles / 700)
  const silhouetteScore = clamp(4 + separation * 0.7 + normalRichness * 0.7 + massRichness * 1.5)
  const geometryScore = clamp(4 + separation * 0.9 + normalRichness * 1.7 + massRichness * 0.5)
  const detailScore = clamp((silhouetteScore + geometryScore) / 2)
  const scaleScore = clamp(
    width + height + depth > 2 && width + height + depth < 120 && min[1] > -0.2 ? 7 + Math.min(2.2, normalRichness) : 4,
  )
  const output = clamp(7 + (grounded ? 1 : -3) + (separateReflection(materials) ? 0.8 : 0) + (normalRichness > 0.35 ? 0.4 : 0))

  const overall = clamp(Math.round((detailScore + scaleScore + output) / 3 * 10) / 10)
  const target = file === 'hero-building.glb' ? 8.5 : file.includes('residential') || file.includes('warehouse') || file.includes('bridge') ? 8.0 : 7.5
  const status =
    !grounded || overall < 7.0
      ? 'REJECTED — rebuild'
      : overall >= target
        ? 'APPROVED'
        : 'REQUIRES RENDER REVIEW'

  rows.push({ file, sizeKB, triangles, width, height, depth, grounded, silhouetteScore, geometryScore, scaleScore, output, overall, status, target })
}

const lines = [
  '# Visual Asset QA',
  '',
  `> Generated by \`npm run assets:visual-qa\` on ${new Date().toISOString().slice(0, 10)}.`,
  '',
  '**Read this table as a technical proxy, not as a photorealism verdict.**',
  '',
  'File validity, triangle counts, material separation and bounding boxes cannot tell you whether an object looks real',
  '— a technically perfect low-poly tree is still a bad tree. This pass exists to catch defects that are cheap to detect',
  '(degenerate scale, floating or sunken origins, missing normals, missing UVs, non-finite data). The realism verdict for',
  'every asset is recorded in `PHOTOREALISM_GATE.md`, and it rests on rendered evidence: the per-object label maps produced',
  'by `scripts/qa/world-shots.mjs` (`LABELS=1`), which show what actually occupies each frame at the real chapter camera.',
  '',
  '| Asset | Size | Triangles | Dimensions (m) | Grounded | Silhouette | Geometry | Scale | Lighting response | Overall | Target | Status |',
  '| --- | ---: | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |',
  ...rows.map((r) =>
    `| ${r.file} | ${r.sizeKB.toFixed(1)} kB | ${r.triangles.toLocaleString()} | ${r.width.toFixed(2)}×${r.height.toFixed(2)}×${r.depth.toFixed(2)} | ${r.grounded ? '✅' : '❌'} | ${r.silhouetteScore.toFixed(1)} | ${r.geometryScore.toFixed(1)} | ${r.scaleScore.toFixed(1)} | ${r.output.toFixed(1)} | ${r.overall.toFixed(1)} | ${r.target} | ${r.status} |`,
  ),
  '',
  '## Scoring rules',
  '',
  '- **Silhouette/Geometry** are driven by production-grade structural detail (micro-components, mullions, railings, equipment) not by raw polygon count alone.',
  '- **Scale** is derived from real-world bounds; everything must read in metres and agree with the door/road/vehicle scale of the experience.',
  '- **Lighting response** is the material separation + normal availability in a physically-lit PBR pipeline.',
  '- **Grounded** requires the lowest vertex to sit at y≈0 so no object floats.',
  '',
]

fs.writeFileSync(REPORT_PATH, lines.join('\n'))
console.log(`→ wrote ${REPORT_PATH}`)
